import fs from 'node:fs';
import assert from 'node:assert/strict';
const h=JSON.parse(fs.readFileSync(new URL('../data/fy26b-holdout-source.json',import.meta.url),'utf8'));
assert.equal(h.examId,'FY26B');
assert.equal(h.role,'final_holdout');
assert.equal(h.trainingExcluded,true);
assert.equal(h.runtimeEnabled,false);
assert.equal(h.officialKeyAvailable,false);
assert.equal(h.listeningAuthority,'unavailable_without_audio');
assert.deepEqual(h.records.map(x=>x.majorQuestion),[1,2,3,4,5,6,7,8]);
const listening=h.records.find(x=>x.majorQuestion===1);
assert.equal(listening.subItems.length,8);
assert.ok(listening.subItems.every(x=>x.answerStatus==='unavailable_without_audio'));
const q4=h.records.find(x=>x.majorQuestion===4);
assert.deepEqual(q4.answerSpec.errorNumbers,[1,4,7,9,10]);
const q5=h.records.find(x=>x.majorQuestion===5);
assert.deepEqual(q5.subItems.find(x=>x.n===8).answer,['イ','エ','キ']);
const q6=h.records.find(x=>x.majorQuestion===6);
assert.deepEqual(q6.subItems.map(x=>x.answer),['C','B','B','B','C','B']);
const q7=h.records.find(x=>x.majorQuestion===7);
assert.equal(q7.subItems.length,4);
assert.equal(h.records.find(x=>x.majorQuestion===8).approxWords,'80-100');
assert.equal(h.passages.length,1);
assert.equal(h.passages[0].transcriptionStatus,'source_checked_visual_v1');
console.log('Rikkyo FY26B holdout supplied-source coverage: CLEAN');
