import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),{chromium,webkit,devices}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),root=process.cwd();
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!p.startsWith(root+path.sep))return res.writeHead(403).end();try{res.setHeader('content-type',({'.js':'text/javascript','.html':'text/html','.json':'application/json','.css':'text/css','.png':'image/png'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const ids=['R25-ENG-A-Q6-4',...Array.from({length:4},(_,i)=>'R26-ENG-A-Q7-'+(i+1))],answers=['リンゴの木を見るのが好きだったから。','Science.','They tested how light affects plant growth.','The plant kept in the dark.','Plants need light, but different light has different effects.'];
try{for(const [name,type,options]of [['desktop',chromium,{viewport:{width:1280,height:900}}],['android',chromium,devices['Pixel 7']],['iphone-webkit',webkit,devices['iPhone 13']]]){const browser=await type.launch(),c=await browser.newContext({...options,serviceWorkers:'block'}),p=await c.newPage(),errors=[],requests=[],dialogs=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',async d=>{dialogs.push(d.message());await d.accept()});let mode='success',delay=0;
await c.route('https://*.workers.dev/**',async route=>{if(!route.request().url().endsWith('/v1/grade-writing'))return route.fulfill({status:200,body:'{"ok":false}'});const payload=route.request().postDataJSON();requests.push(payload);if(delay)await new Promise(r=>setTimeout(r,delay));if(mode==='network')return route.abort();if(mode==='quota')return route.fulfill({status:429,contentType:'application/json',body:'{"error":"usage_limit_reached"}'});if(mode==='invalid')return route.fulfill({status:200,contentType:'application/json',body:'{"score":12}'});const {task,answer}=payload,ja=task.taskId===ids[0],correct=!answer.includes('History');await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({schoolId:'rikkyo',questionId:task.taskId,scope:'exam',skill:task.skill,official:false,feedbackSchema:'reading-v1',score:correct?12:8,maxScore:12,semantic:[correct?1:0,1,1,1,0,0],breakdown:['本文の正確さ','言葉の正確さ','明確さ'].map((name,i)=>({name,earned:!correct&&i===0?0:4,max:4})),issues:[],strengths:['根拠を確認できます'],reasons:[],revisedExample:answer,contentCorrect:correct,learningCorrect:correct,answerLanguage:ja?'ja':'en',evidence:ja?'Goldie liked to see the apple tree through the windows of the living room when he was alive.':'Dr. Smith is a science teacher.',explanationJa:'本文の根拠に基づく評価です。',nextPractice:[],generatedAt:new Date().toISOString()})});});
await p.goto(url+'/index.html');await p.waitForFunction(()=>window.__RIKKYO_APP_READY__);await p.evaluate(()=>localStorage.setItem('waseshibu.adaptive.v3','WASEDA-SENTINEL'));
for(const [i,id]of ids.entries()){await p.evaluate(exam=>{__RIKKYO_APP__.resetForTest();__RIKKYO_APP__.beginAttempt(exam)},i===0?'FY25A':'FY26A');const box=p.locator('#answer-'+id);assert.ok(!(await box.innerText()).includes('自己採点の記述問題'));await box.locator('textarea').fill(answers[i]);await box.getByRole('button',{name:'AI添削する',exact:true}).click();await p.waitForFunction(id=>document.querySelector('#reading-tools-'+id).textContent.includes('添削を保存'),id);assert.equal((await p.evaluate(()=>__RIKKYO_APP__.getState())).attempts.length,0);assert.ok(await box.locator('.ai-feedback').isVisible());assert.doesNotMatch(await box.locator('.ai-score-head').innerText(),/\d+語/); // No invented word-count requirement.
await box.locator('textarea').fill(answers[i]+' ');assert.ok(await box.locator('.ai-feedback').isVisible());await box.locator('textarea').fill(answers[i]+' changed');assert.equal(await box.locator('.ai-feedback').count(),0);assert.ok((await box.innerText()).includes('前の評価は無効'));}
const id=ids[1],box=p.locator('#answer-'+id);await box.locator('textarea').fill('Science.');
for(const failure of['network','quota','invalid']){mode=failure;const before=await p.evaluate(()=>__RIKKYO_APP__.getState());await p.getByRole('button',{name:'解答を確認して弱点を登録',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.grade-button').disabled);const after=await p.evaluate(()=>__RIKKYO_APP__.getState());assert.deepEqual(after.currentAttempt.responses,before.currentAttempt.responses);assert.deepEqual(after.weak,before.weak);assert.deepEqual(after.attempts,before.attempts);assert.ok((await box.innerText()).includes('答案は保存'));}mode='success';
delay=800;const beforeRace=requests.length;await box.getByRole('button',{name:'AI添削する',exact:true}).click();await p.evaluate(id=>{void __RIKKYO_APP__.gradeReading(id)},id);await box.locator('textarea').fill('History.');await p.waitForFunction(id=>document.querySelector('#reading-tools-'+id).textContent.includes('答案が変更'),id);assert.equal(requests.length,beforeRace+1);assert.equal(await box.locator('.ai-feedback').count(),0);delay=0;
// Submit obtains every missing AI assessment, no self-assessment dialog; content errors become learning weaknesses.
for(let i=1;i<ids.length;i++)await p.locator('#answer-'+ids[i]+' textarea').fill(i===1?'History.':answers[i]);const beforeSubmit=requests.length;await p.getByRole('button',{name:'解答を確認して弱点を登録',exact:true}).click();await p.waitForFunction(()=>__RIKKYO_APP__.getState().attempts.length===1);const graded=await p.evaluate(()=>__RIKKYO_APP__.getState());assert.equal(requests.length,beforeSubmit+4);assert.equal(graded.currentAttempt,null);assert.equal(graded.attempts[0].results[id],false);for(const id of ids.slice(2))assert.equal(graded.attempts[0].results[id],true);assert.equal(graded.attempts[0].scoreModel,'unscored');assert.ok(dialogs.every(t=>!t.includes('自己採点')));assert.equal(await p.evaluate(()=>localStorage.getItem('waseshibu.adaptive.v3')),'WASEDA-SENTINEL');
// Reload + export/import retain answers and evidence. An in-flight response cannot modify a replaced state.
await p.reload();await p.waitForFunction(()=>window.__RIKKYO_APP_READY__);assert.deepEqual((await p.evaluate(()=>__RIKKYO_APP__.getState())).attempts,graded.attempts);
await p.evaluate(()=>{__RIKKYO_APP__.beginAttempt('FY25A');__RIKKYO_APP__.setResponse('R25-ENG-A-Q6-4','リンゴの木を見るのが好きだったから。')});await p.locator('#answer-'+ids[0]).getByRole('button',{name:'AI添削する',exact:true}).click();await p.waitForFunction(()=>__RIKKYO_APP__.getState().currentAttempt.readingFeedback?.['R25-ENG-A-Q6-4']);const download=p.waitForEvent('download');await p.evaluate(()=>__RIKKYO_APP__.exportData());const backup=JSON.parse(fs.readFileSync(await(await download).path(),'utf8'));await p.evaluate(()=>__RIKKYO_APP__.resetForTest());await p.evaluate(b=>{__RIKKYO_APP__.importPayload(b,'replace');__RIKKYO_APP__.goto('exam')},backup);assert.ok(await p.locator('#answer-'+ids[0]+' .ai-feedback').isVisible());
delay=800;await p.locator('#answer-'+ids[0]).getByRole('button',{name:'AI添削する',exact:true}).click();await p.evaluate(b=>__RIKKYO_APP__.importPayload(b,'replace'),backup);await p.waitForTimeout(1000);assert.deepEqual((await p.evaluate(()=>__RIKKYO_APP__.getState())).currentAttempt.readingFeedback,backup.state.currentAttempt.readingFeedback);assert.deepEqual(errors,[]);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));fs.mkdirSync('test-results',{recursive:true});await p.screenshot({path:'test-results/reading-'+name+'.png',fullPage:true});console.log('PASS reading',name,'5 inline tasks, stale/duplicate/race, error-safe submit, AI learning outcomes, reload/backup/import, Waseda isolation');await c.close();await browser.close();}}finally{server.close()}
