import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),root=process.cwd();
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost').pathname,f=path.resolve(root,'.'+(u==='/'?'/index.html':u));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();try{res.setHeader('content-type',({'.js':'text/javascript','.html':'text/html','.json':'application/json','.css':'text/css'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{})});
try{for(const width of [390,1280]){const context=await browser.newContext({viewport:{width,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>(errors.push(e.message),console.error(e.message)));await context.route('https://*.workers.dev/**',r=>r.fulfill({status:200,contentType:'application/json',body:'{"ok":false}'}));await page.goto(origin);await page.waitForFunction(()=>window.__RIKKYO_APP_READY__);await page.getByRole('button',{name:'使い方',exact:true}).click();await page.getByRole('button',{name:'英作文',exact:true}).click();
const answer='One morning I woke up and found that I could speak to birds. I felt excited, but a small bird asked me to help its friend.';await page.locator('#writingText').fill(answer);await page.getByLabel('新しく得た能力を具体的に書いた').check();const saved=await page.evaluate(()=>__RIKKYO_APP__.getState());assert.equal(saved.writingPractice.text,answer);assert.equal(saved.writingPractice.checks.ability,true);assert.equal(saved.attempts.length,0);assert.equal(saved.drillLog.length,0);
await page.reload();await page.waitForFunction(()=>window.__RIKKYO_APP_READY__);await page.getByRole('button',{name:'使い方',exact:true}).click();await page.getByRole('button',{name:'英作文',exact:true}).click();assert.equal(await page.locator('#writingText').inputValue(),answer);assert.equal(await page.getByLabel('新しく得た能力を具体的に書いた').isChecked(),true);
const downloadPromise=page.waitForEvent('download');await page.evaluate(()=>__RIKKYO_APP__.exportData());const backup=JSON.parse(fs.readFileSync(await(await downloadPromise).path(),'utf8'));assert.equal(backup.state.writingPractice.text,answer);
await page.evaluate(()=>__RIKKYO_APP__.resetForTest());await page.evaluate(b=>__RIKKYO_APP__.importPayload(b,'replace'),backup);assert.equal(await page.locator('#writingText').inputValue(),answer);await page.locator('#writingText').fill(answer+' I helped.');assert.equal(await page.getByLabel('新しく得た能力を具体的に書いた').isChecked(),false);
await page.evaluate(b=>__RIKKYO_APP__.importPayload(b,'merge'),backup);assert.ok((await page.locator('#writingText').inputValue()).endsWith('I helped.'));assert.deepEqual(errors,[]);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));console.log('Writing browser PASS',width,'draft/reload/checklist/export/reset/import/merge/no scores');await context.close();}}finally{await browser.close();server.close();}
