import fs from 'node:fs';
import assert from 'node:assert/strict';
const p=JSON.parse(fs.readFileSync(new URL('../data/writing-runtime-policy.json',import.meta.url),'utf8'));
assert.equal(p.status,'unofficial_story_ai_feedback');
assert.equal(p.aiWritingEnabled,true);
assert.equal(p.officialMarkingAuthorityAvailable,false);
assert.equal(p.rules.doNotInventPictureAssets,true);
assert.equal(p.rules.doNotAddToExamScores,true);
assert.deepEqual(p.tasks.map(x=>x.examId),['FY25A','FY25B','FY26A','FY26B']);
assert.ok(p.tasks.every(x=>x.runtimeEnabled===true&&x.approxWords==='80-100'));
assert.ok(p.tasks.filter(x=>x.type==='picture_story_writing').every(x=>/Source verified/i.test(x.reason)));
console.log('Rikkyo writing runtime policy: CLEAN');
