(function(root){
'use strict';
const checks=[['ability','新しく得た能力を具体的に書いた'],['events','その日に起きたことを書いた'],['feelings','自分の気持ちを書いた'],['problem','問題や冒険と、その展開を書いた'],['pictures','原本の絵の順序・内容に沿って書いた'],['opening','指定の書き出しから始めた'],['door','学校の不思議な扉を通った後の物語を書いた'],['sequence','出来事の順序とつながりを読み直した'],['language','主語・動詞・時制・つづりを読み直した']];
const count=text=>(String(text||'').match(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g)||[]).length;
function normalize(raw){const x=raw&&typeof raw==='object'?raw:{},selected={};for(const [key]of checks)selected[key]=x.checks?.[key]===true;return{text:typeof x.text==='string'?x.text.slice(0,10000):'',checks:selected,updatedAt:typeof x.updatedAt==='string'?x.updatedAt:null,history:Array.isArray(x.history)?x.history.filter(v=>v&&typeof v.answer==='string'&&v.answer.length<=1200&&v.feedback&&root.ENGLISH_WRITING_FEEDBACK?.validateAIFeedback(v.feedback,28)).slice(-20):[]};}
function render(raw,prompt,h,task={taskId:'FY26A:Q8'},pending=false){const x=normalize(raw);return '<section class="card hero"><h2>英作文・AI添削</h2><p>'+h(task.taskId.replace(':Q',' 大問'))+'・80〜100語の物語</p></section><section class="card">'+(task.image?'<img src="'+h(task.image)+'" alt="原本の絵作文・3枚の絵と設問" style="width:100%;height:auto">':'')+'<p>'+h(prompt)+'</p><p class="muted">過去問の指示に基づく練習です。下の項目はアプリ独自の見直し用で、学校公式の採点基準ではありません。自己確認のチェックで正解・習得とは判定しません。</p><label for="writingText">自分の英文</label><textarea id="writingText" rows="10" maxlength="10000" style="width:100%;box-sizing:border-box" oninput="__RIKKYO_APP__.saveWritingText(this.value)">'+h(x.text)+'</textarea><p><output id="writingCount" aria-live="polite">'+count(x.text)+'</output> 語（英語の語を概算。ハイフン・アポストロフィを含む語は1語）</p><p>80〜100語を目安に、内容と読みやすさを確認してください。語数は学習用評価の一項目です。学校公式の点数ではなく、入試得点には加算しません。</p><button id="writingGrade" type="button" '+(pending?'disabled ':'')+'onclick="__RIKKYO_APP__.gradeWriting()">AIで学習用採点・再提出</button><div id="writingStatus" role="status" aria-live="polite">'+(pending?'答案を確認しています…':'')+'</div><div id="writingFeedback">'+feedback(x,h)+'</div><fieldset><legend>書き終えたら一つずつ確認</legend>'+checks.filter(([key])=>!['ability','pictures','opening','door'].includes(key)||(task.skill==='picture_story_writing'?['pictures','opening'].includes(key):task.taskId==='FY26B:Q8'?key==='door':key==='ability')).map(([key,label])=>'<label style="display:block;margin:12px 0"><input type="checkbox" '+(x.checks[key]?'checked ':'')+'onchange="__RIKKYO_APP__.saveWritingCheck(\''+key+'\',this.checked)"> '+h(label)+'</label>').join('')+'</fieldset><p>英文はこの端末に自動保存され、「使い方」のバックアップにも含まれます。AI添削を押すと英文をCloudflareのAIへ送信します。添削履歴はこの端末とバックアップに保存されます。</p><p class="muted">FY26Bは最終試験を原本で完了した後だけ添削できます。</p></section>';}
function feedback(raw,h){const x=normalize(raw),latest=x.history.at(-1);if(!latest)return '';const same=latest.answer===x.text.trim();let html=same?root.ENGLISH_WRITING_FEEDBACK.aiFeedbackMarkup(latest.feedback,x.text):'<p class="notice">答案を変更したため、前の評価は無効です。再提出してください。</p>';if(same&&latest.feedback.nextPractice?.length)html+='<h3>次回の練習ポイント</h3><ul>'+latest.feedback.nextPractice.map(v=>'<li>'+h(v)+'</li>').join('')+'</ul>';if(x.history.length>1){html+='<details><summary>改善前後の評価・提出履歴（'+x.history.length+'回）</summary>';for(const row of x.history)html+='<article><p>'+h(row.generatedAt||'')+'：学習用 '+Number(row.feedback.score)+'/28</p><p>'+h(row.answer)+'</p><div>'+root.ENGLISH_WRITING_FEEDBACK.aiFeedbackMarkup(row.feedback,row.answer)+'</div></article>';html+='</details>'}return html}
root.RIKKYO_WRITING_PRACTICE=Object.freeze({checks,count,normalize,render,feedback});
})(typeof globalThis!=='undefined'?globalThis:this);
